# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [8]:
lst1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
arr1 = np.array(lst1)
print(arr1)

lst1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
arr1 = np.array(lst1)
print(arr1)

arr1 = np.ones((1,5,5))
print (arr1)

[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [13]:
arr2 = np.random.randn (3,3,3)
print(arr2)

arr2b = arr2.reshape(27)
print(arr2b)

[[[ 0.09734529 -1.56611002 -1.36887326]
  [-0.53884511  1.39756042 -0.36555488]
  [-0.65546547 -0.7742911   0.17131235]]

 [[ 0.8749602   1.39734218  1.96061036]
  [ 0.3596371  -0.13856278  0.20877425]
  [-1.2677523  -0.42619565  0.61807114]]

 [[-0.52135947  0.16400861  0.80648358]
  [ 0.28766527  0.11622674 -0.17899199]
  [-0.11873742 -3.14552094  0.05483921]]]
[ 0.09734529 -1.56611002 -1.36887326 -0.53884511  1.39756042 -0.36555488
 -0.65546547 -0.7742911   0.17131235  0.8749602   1.39734218  1.96061036
  0.3596371  -0.13856278  0.20877425 -1.2677523  -0.42619565  0.61807114
 -0.52135947  0.16400861  0.80648358  0.28766527  0.11622674 -0.17899199
 -0.11873742 -3.14552094  0.05483921]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [15]:
arr3 = np.linspace (1, 10, 20, dtype= "int")
print (arr3)

[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [18]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
20

In [ ]:
#Code goes here

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Code come here


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [ ]:
# Code comes here

## 2.6 

Calculate the sum of each row in `a`.

In [ ]:
# Code comes here

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [19]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [25]:
carbon_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv", sep=",", header=0, encoding="ISO-8859-1")
carbon_df.head(11) #printing on the first 11 rows

country             food_category  consumption  co2_emmission
0   Argentina                      Pork        10.51          37.20
1   Argentina                   Poultry        38.66          41.53
2   Argentina                      Beef        55.48        1712.00
3   Argentina               Lamb & Goat         1.56          54.63
4   Argentina                      Fish         4.36           6.96
5   Argentina                      Eggs        11.39          10.46
6   Argentina        Milk - inc. cheese       195.08         277.87
7   Argentina  Wheat and Wheat Products       103.11          19.66
8   Argentina                      Rice         8.77          11.22
9   Argentina                  Soybeans         0.00           0.00
10  Argentina   Nuts inc. Peanut Butter         0.49           0.87

## 2.10 

How many rows and columns are there in the dataframe?

In [24]:
print(len(carbon_df)) #rows in the dataframe
print(len(carbon_df.columns)) #columns in the dataframe

1430
4


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [33]:
carbon_mn = carbon_df["co2_emmission"].mean()
print(carbon_mn)

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [74]:
carbon_df.loc[carbon_df['co2_emmission'].idxmax()]

country          Argentina
food_category         Beef
consumption          55.48
co2_emmission       1712.0
Name: 2, dtype: object

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [48]:
countries_df = carbon_df.query('co2_emmission > 1000')
print(countries_df)
print(len(countries_df))
print('')

       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94
5



## 2.14

Which country consumes the least amount of beef per person per year?


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.